"""Add indexes and unique constraint

Revision ID: 120edd195151
Revises: 42da372e96c0
Create Date: 2025-04-24 13:09:38.806914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120edd195151'
down_revision: Union[str, None] = '42da372e96c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_exchange_rate_date', 'exchange_rates', ['from_currency', 'to_currency', 'rate_date'])
    op.create_index('ix_enterprise_id', 'indicator_values', ['enterprise_id'], unique=False)
    op.create_index('ix_indicator_id', 'indicator_values', ['indicator_id'], unique=False)
    op.create_index('ix_value_date', 'indicator_values', ['value_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_value_date', table_name='indicator_values')
    op.drop_index('ix_indicator_id', table_name='indicator_values')
    op.drop_index('ix_enterprise_id', table_name='indicator_values')
    op.drop_constraint('uix_exchange_rate_date', 'exchange_rates', type_='unique')
    # ### end Alembic commands ###
