"""Initial schema

Revision ID: 42da372e96c0
Revises: 
Create Date: 2025-04-23 22:40:37.205101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42da372e96c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_exchange_rates_from_to_date', table_name='exchange_rates')
    op.drop_index('idx_indicator_values_enterprise_id', table_name='indicator_values')
    op.drop_index('idx_indicator_values_value_date', table_name='indicator_values')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_index('idx_indicator_values_value_date', 'indicator_values', ['value_date'], unique=False)
    op.create_index('idx_indicator_values_enterprise_id', 'indicator_values', ['enterprise_id'], unique=False)
    op.create_index('idx_exchange_rates_from_to_date', 'exchange_rates', ['from_currency', 'to_currency', 'rate_date'], unique=False)
    # ### end Alembic commands ###
